class Discriminator(object):
    """Class containing code to discriminate columns in the .csv file"""
    def __init__(self):
        self.columns = [
        ' Source IP',
        ' Source Port',
        ' Destination IP',
        ' Destination Port',
        ' Flow Duration',
        ' Total Fwd Packets',
        ' Total Backward Packets',
        'Total Length of Fwd Packets',
        ' Total Length of Bwd Packets',
        ' Fwd Packet Length Max',
        ' Fwd Packet Length Min',
        ' Fwd Packet Length Mean',
        ' Fwd Packet Length Std',
        'Bwd Packet Length Max',
        ' Bwd Packet Length Min',
        ' Bwd Packet Length Mean',
        'Flow Bytes/s',
        ' Flow Packets/s',
        ' Flow IAT Mean',
        ' Flow IAT Std',
        ' Flow IAT Max',
        ' Flow IAT Min',
        'Fwd IAT Total',
        ' Fwd IAT Mean',
        ' Fwd IAT Std',
        ' Fwd IAT Max',
        ' Fwd IAT Min',
        'Bwd IAT Total',
        ' Bwd IAT Mean',
        ' Bwd IAT Max',
        ' Bwd IAT Min',
        ' Fwd Header Length',
        ' Bwd Header Length',
        'Fwd Packets/s',
        ' Bwd Packets/s',
        ' Min Packet Length',
        ' Max Packet Length',
        ' Packet Length Mean',
        ' Packet Length Std',
        ' Packet Length Variance',
        ' Average Packet Size',
        ' Avg Fwd Segment Size',
        ' Avg Bwd Segment Size',
        'Subflow Fwd Packets',
        ' Subflow Fwd Bytes',
        ' Subflow Bwd Packets',
        ' Subflow Bwd Bytes',
        'Active Mean',
        ' Active Std',
        ' Active Max',
        ' Active Min',
        'Idle Mean',
        ' Idle Std',
        ' Idle Max',
        ' Idle Min',
        ' Label'
        ]

        self.columns_to_retain = [
        ' Source IP',
        ' Source Port',
        ' Destination IP',
        ' Destination Port',
        ' Label'
        ]
