version: '3'
services:
  target:
    build:
      context: docker/server/
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    container_name: target

  ddos:
    build:
      context: docker/ddos/
      dockerfile: Dockerfile
    restart: always
    container_name: ddos

  normal_traffic:
    build:
      context: docker/normal_traffic
      dockerfile: Dockerfile
    restart: always
    container_name: normal_traffic

  slowloris:
    build:
      context: docker/slowloris
      dockerfile: Dockerfile
    restart: always
    container_name: slowloris
