version: '3'
services:
  target:
    build:
      context: docker/server/
      dockerfile: Dockerfile
    ports:
            - "8080:80"
    restart: always
    container_name: server

  attacker:
    build:
      context: docker/attacker/
      dockerfile: Dockerfile
    restart: always
    container_name: attacker
