version: '3'
services:
  target:
    build:
      context: docker/server/
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    container_name: target

  attacker:
    build:
      context: docker/attacker/
      dockerfile: Dockerfile
    restart: always
    container_name: attacker
